"use client";

import { Briefcase, GraduationCap, IdCard, TrendingUp } from "lucide-react";
import {
  EmploymentStatus,
  ExperienceBand,
  PhysioRegistrationData,
  PHYSIO_QUALIFICATIONS,
} from "../_lib/types";
import {
  CheckboxCard,
  RadioCard,
  SectionCard,
  TextArea,
  TextInput,
} from "./FormControls";
import { StepNav } from "./StepNav";

const EXPERIENCE_OPTIONS: { key: ExperienceBand; label: string }[] = [
  { key: "fresher", label: "Fresher" },
  { key: "1-3", label: "1–3 Years" },
  { key: "3-5", label: "3–5 Years" },
  { key: "5-10", label: "5–10 Years" },
  { key: "10+", label: "10+ Years" },
];

const EMPLOYMENT_OPTIONS: { key: EmploymentStatus; label: string }[] = [
  { key: "full-time", label: "Working Full Time" },
  { key: "part-time", label: "Working Part Time" },
  { key: "freelance", label: "Freelance" },
  { key: "not-working", label: "Not Working" },
];

const STUDENT_PREFIX = "PT-STU-";

function generateStudentRegistrationNumber(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  const randomPart = Math.random().toString(36).substring(2, 7).toUpperCase();
  return `${STUDENT_PREFIX}${timestamp}-${randomPart}`;
}

export function Step3Professional({
  data,
  update,
  onNext,
  onBack,
}: {
  data: PhysioRegistrationData;
  update: (patch: Partial<PhysioRegistrationData>) => void;
  onNext: () => void;
  onBack: () => void;
}) {
  const isStudent = data.isStudent ?? false;

  const canContinue = isStudent
    ? data.registrationNumber.trim() !== ""
    : data.registrationNumber.trim() !== "" && data.statePhysioCouncil.trim() !== "";

  const handleStudentToggle = (next: boolean) => {
    if (next) {
      update({
        isStudent: true,
        registrationNumber: generateStudentRegistrationNumber(),
        statePhysioCouncil: "",
        registrationExpiryDate: "",
        yearsOfExperience: "fresher",
      });
    } else {
      const wasAutoGenerated = data.registrationNumber.startsWith(STUDENT_PREFIX);
      update({
        isStudent: false,
        registrationNumber: wasAutoGenerated ? "" : data.registrationNumber,
      });
    }
  };

  return (
    <div className="space-y-5">
      <SectionCard icon={<GraduationCap size={18} />} title="Qualification">
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {PHYSIO_QUALIFICATIONS.map((q) => (
            <RadioCard
              key={q}
              label={q}
              selected={data.qualification === q}
              onSelect={() => update({ qualification: q })}
            />
          ))}
        </div>
      </SectionCard>

      <SectionCard icon={<IdCard size={18} />} title="Registration Details">
        <div className="mb-4">
          <CheckboxCard
            label="I Don't have a registration number yet"
            description="We'll generate a temporary registration number for you, which you can update later once you receive your official council registration number."
            checked={isStudent}
            onChange={handleStudentToggle}
            icon={<GraduationCap size={18} />}
          />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <TextInput
            label={
              isStudent
                ? "Registration Number (auto-generated)"
                : "State Physiotherapy Council Registration Number"
            }
            required
            value={data.registrationNumber}
            onChange={(e) => update({ registrationNumber: e.target.value })}
            readOnly={isStudent}
            className={isStudent ? "bg-neutral-100 cursor-not-allowed" : ""}
          />

          {!isStudent && (
            <>
              <TextInput
                label="State Physiotherapy Council"
                required
                placeholder="e.g. Karnataka State Physiotherapy Council"
                value={data.statePhysioCouncil}
                onChange={(e) => update({ statePhysioCouncil: e.target.value })}
              />
              <TextInput
                label="Registration Expiry Date (if applicable)"
                type="date"
                value={data.registrationExpiryDate}
                onChange={(e) => update({ registrationExpiryDate: e.target.value })}
              />
            </>
          )}
        </div>

        {isStudent && (
          <p className="mt-3 text-xs text-neutral-400">
            Your registration number is unique to your account and can be used for verification
            purposes. You can update it later once you receive your official council registration
            number.
          </p>
        )}
      </SectionCard>

      {!isStudent && (
        <SectionCard icon={<TrendingUp size={18} />} title="Years of Experience">
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
            {EXPERIENCE_OPTIONS.map((opt) => (
              <RadioCard
                key={opt.key}
                label={opt.label}
                selected={data.yearsOfExperience === opt.key}
                onSelect={() => update({ yearsOfExperience: opt.key })}
              />
            ))}
          </div>
        </SectionCard>
      )}

      <SectionCard icon={<Briefcase size={18} />} title="Current Employment Status">
        <div className="grid grid-cols-2 gap-3 mb-4">
          {EMPLOYMENT_OPTIONS.map((opt) => (
            <RadioCard
              key={opt.key}
              label={opt.label}
              selected={data.employmentStatus === opt.key}
              onSelect={() => update({ employmentStatus: opt.key })}
            />
          ))}
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <TextInput
            label="Current Clinic / Hospital"
            value={data.currentClinic}
            onChange={(e) => update({ currentClinic: e.target.value })}
          />
          <TextArea
            label="Previous Clinics (optional)"
            rows={1}
            value={data.previousClinics}
            onChange={(e) => update({ previousClinics: e.target.value })}
          />
        </div>
      </SectionCard>

      <StepNav onBack={onBack} onNext={onNext} nextDisabled={!canContinue} />
    </div>
  );
}